cmd: make config path configurable
edgelesssys/uplosi pull request #56
Opened 2024-04-09 09:05 UTC by msanft

Support setting a path to a config file via the command line.

2024-04-09 14:31 UTC, katexochen requested changes

2024-04-09 14:31 UTC, katexochen commented on cmd.go
> +	cmd.Flags().StringP("config", "c", "", fmt.Sprintf("path to directory %s or %s resides in", configName, configDir))
```suggestion
	cmd.Flags().StringP("config", "c", "", fmt.Sprintf("path to directory %s and %s resides in", configName, configDir))
```

2024-04-09 14:31 UTC, katexochen commented on cmd.go
> +	}
```suggestion
	configLocation := path.Join(configPath, configName)
	configDirLocation := path.Join(configPath, configDir)
```
Will just return the default path if configPath is empty

2024-04-15 06:26 UTC, malt3 approved these changes

2024-04-15 07:03 UTC, merged