Add TPM PCR measurement precalculation
edgelesssys/uplosi pull request #74
Opened 2024-06-05 10:56 UTC by msanft

This adds the `uplosi precalculate-measurements` command for ahead-of-time calculation of TPM PCR measurements from an image.

Precalculation code is based on what we have in Constellation right now, with slight modifications to make it work for both Constellation and Continuum images.

It's not documented yet, but also not hidden. I wasn't exactly sure how to go about this.

2024-06-05 12:24 UTC, daniel-weisse reviewed
Once this is merged and a new release is cut, we can remove the measurement code from the Constellation repo and use this tool instead, correct?

2024-06-05 12:24 UTC, daniel-weisse commented on precalculate-measurements.go
> +		Use:   "precalculate-measurements <image>",
```suggestion
		Use:   "measurements <image>",
```
nit: just using `uplosi measurements <image>` sounds a lot better

2024-06-05 12:24 UTC, daniel-weisse commented on measured-boot/measure/pcr09.go
> +	// }
If the cmdline can be either Null byte or newline terminated, we can should check for this here

2024-06-05 12:24 UTC, daniel-weisse commented on precalculate-measurements.go
> +	}
If the flag is empty, we should print the measurements instead of just returning nil (unless that already happened somewhere else)

2024-06-06 14:31 UTC, daniel-weisse approved these changes
Please let @katexochen also review before merging

2024-06-07 12:21 UTC, katexochen requested changes

2024-06-07 12:21 UTC, katexochen commented on measured-boot/measure/measure_test.go
> +	goleak.VerifyTestMain(m, goleak.IgnoreAnyFunction("github.com/bazelbuild/rules_go/go/tools/bzltestutil.RegisterTimeoutHandler.func1"))
again, I think the ignore can be removed.

2024-06-07 12:21 UTC, katexochen commented on measurements.go
> +	dissectToolchain := loadToolchain("DISSECT_TOOLCHAIN", "systemd-dissect")
This needs to be documented.

2024-06-07 12:21 UTC, katexochen commented on measurements.go
> +func newMeasurementsCmd() *cobra.Command {
Please add a section to the readme documenting the command and explaining what is currently does and what not.

2024-06-10 07:14 UTC, msanft commented on measured-boot/measure/pcr09.go
> +	fmt.Println(cmdline)
oopsie woopsie

2024-06-10 07:14 UTC, katexochen commented on README.md
> +> is only tested in a very specific environment and should for general production use-cases.
```suggestion
> is only tested in a very specific environment and should ??? for general production use-cases.
```

2024-06-10 07:19 UTC, katexochen approved these changes

2024-06-10 07:19 UTC, merged